COPY GTFS_NAME.agency(AGENCY_COLUMNS) FROM 'GTFS_FOLDER/GTFS_NAME/gtfs/agency.txt' DELIMITER ',' CSV HEADER;

COPY GTFS_NAME.routes(ROUTES_COLUMNS) FROM 'GTFS_FOLDER/GTFS_NAME/gtfs/routes.txt' DELIMITER ',' CSV HEADER;

COPY GTFS_NAME.fare_rules(FARE_RULES_COLUMNS) FROM 'GTFS_FOLDER/GTFS_NAME/gtfs/fare_rules.txt' DELIMITER ',' CSV HEADER;

COPY GTFS_NAME.fare_attributes(FARE_ATTRIBUTES_COLUMNS) FROM 'GTFS_FOLDER/GTFS_NAME/gtfs/fare_attributes.txt' DELIMITER ',' CSV HEADER;

COPY GTFS_NAME.stops(STOPS_COLUMNS) FROM 'GTFS_FOLDER/GTFS_NAME/gtfs/stops.txt' DELIMITER ',' CSV HEADER;

COPY GTFS_NAME.shapes(SHAPES_COLUMNS) FROM 'GTFS_FOLDER/GTFS_NAME/gtfs/shapes.txt' DELIMITER ',' CSV HEADER;

COPY GTFS_NAME.frequencies(FREQUENCIES_COLUMNS) FROM 'GTFS_FOLDER/GTFS_NAME/gtfs/frequencies.txt' DELIMITER ',' CSV HEADER;

COPY GTFS_NAME.feed_info(FEED_INFO_COLUMNS) FROM 'GTFS_FOLDER/GTFS_NAME/gtfs/feed_info.txt' DELIMITER ',' CSV HEADER;

COPY GTFS_NAME.calendar(CALENDAR_COLUMNS) FROM 'GTFS_FOLDER/GTFS_NAME/gtfs/calendar.txt' DELIMITER ',' CSV HEADER;

COPY GTFS_NAME.calendar_dates(CALENDAR_DATES_COLUMNS) FROM 'GTFS_FOLDER/GTFS_NAME/gtfs/calendar_dates.txt' DELIMITER ',' CSV HEADER;

COPY GTFS_NAME.trips(TRIPS_COLUMNS) FROM 'GTFS_FOLDER/GTFS_NAME/gtfs/trips.txt' DELIMITER ',' CSV HEADER;

COPY GTFS_NAME.stop_times(STOP_TIMES_COLUMNS) FROM 'GTFS_FOLDER/GTFS_NAME/gtfs/stop_times.txt' DELIMITER ',' CSV HEADER;

COPY GTFS_NAME.transfer(TRANSFER_COLUMNS) FROM 'GTFS_FOLDER/GTFS_NAME/gtfs/transfer.txt' DELIMITER ',' CSV HEADER;
