-- ALTER TABLE GTFS_NAME.stop_times ENABLE TRIGGER ALL;
-- ALTER TABLE GTFS_NAME.frequencies ENABLE TRIGGER ALL;
-- ALTER TABLE GTFS_NAME.trips ENABLE TRIGGER ALL;
-- ALTER TABLE GTFS_NAME.calendar_dates ENABLE TRIGGER ALL;
-- ALTER TABLE GTFS_NAME.routes ENABLE TRIGGER ALL;
-- ALTER TABLE GTFS_NAME.fare_rules ENABLE TRIGGER ALL;
-- ALTER TABLE GTFS_NAME.transfer ENABLE TRIGGER ALL;

-- COMMIT;
