-- ALTER TABLE GTFS_NAME.stop_times DISABLE TRIGGER ALL;
-- ALTER TABLE GTFS_NAME.frequencies DISABLE TRIGGER ALL;
-- ALTER TABLE GTFS_NAME.trips DISABLE TRIGGER ALL;
-- ALTER TABLE GTFS_NAME.calendar_dates DISABLE TRIGGER ALL;
-- ALTER TABLE GTFS_NAME.routes DISABLE TRIGGER ALL;
-- ALTER TABLE GTFS_NAME.fare_rules DISABLE TRIGGER ALL;
-- ALTER TABLE GTFS_NAME.transfer DISABLE TRIGGER ALL;


-- ALTER TABLE GTFS_NAME.stop_times ALTER CONSTRAINT fk_GTFS_NAME_stop_times_stop DEFERRABLE;
-- ALTER TABLE GTFS_NAME.stop_times ALTER CONSTRAINT fk_GTFS_NAME_stop_times_trip DEFERRABLE;
-- ALTER TABLE GTFS_NAME.frequencies ALTER CONSTRAINT fk_GTFS_NAME_frequencies_trip DEFERRABLE;
-- ALTER TABLE GTFS_NAME.trips ALTER CONSTRAINT fk_GTFS_NAME_trips_calendar DEFERRABLE;
-- ALTER TABLE GTFS_NAME.trips ALTER CONSTRAINT fk_GTFS_NAME_trips_shape DEFERRABLE;
-- ALTER TABLE GTFS_NAME.trips ALTER CONSTRAINT fk_GTFS_NAME_trips_route DEFERRABLE;
-- ALTER TABLE GTFS_NAME.calendar_dates ALTER CONSTRAINT fk_GTFS_NAME_calendar_dates_calendar DEFERRABLE;
-- ALTER TABLE GTFS_NAME.routes ALTER CONSTRAINT fk_GTFS_NAME_routes_agency DEFERRABLE;
-- ALTER TABLE GTFS_NAME.fare_rules ALTER CONSTRAINT fk_GTFS_NAME_fare_rules_route DEFERRABLE;
-- ALTER TABLE GTFS_NAME.transfer ALTER CONSTRAINT fk_GTFS_NAME_transfer_to_stop DEFERRABLE;
-- ALTER TABLE GTFS_NAME.transfer ALTER CONSTRAINT fk_GTFS_NAME_transfer_from_stop DEFERRABLE;

-- BEGIN

-- SET CONSTRAINTS fk_GTFS_NAME_stop_times_stop DEFERRED;
-- SET CONSTRAINTS fk_GTFS_NAME_stop_times_trip DEFERRED;
-- SET CONSTRAINTS fk_GTFS_NAME_frequencies_trip DEFERRED;
-- SET CONSTRAINTS fk_GTFS_NAME_trips_calendar DEFERRED;
-- SET CONSTRAINTS fk_GTFS_NAME_trips_shape DEFERRED;
-- SET CONSTRAINTS fk_GTFS_NAME_trips_route DEFERRED;
-- SET CONSTRAINTS fk_GTFS_NAME_calendar_dates_calendar DEFERRED;
-- SET CONSTRAINTS fk_GTFS_NAME_routes_agency DEFERRED;
-- SET CONSTRAINTS fk_GTFS_NAME_transfer_to_stop DEFERRED;
-- SET CONSTRAINTS fk_GTFS_NAME_fare_rules_route DEFERRED;

-- SET CONSTRAINTS fk_GTFS_NAME_transfer_from_stop DEFERRED;

