apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fleet-simulator
  labels:
    app: fleet-simulator
    version: {{ .Values.docker.tag }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  minReadySeconds: 120
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: fleet-simulator
    spec:
      containers:
      - name: fleet-simulator
        image: '{{ .Values.docker.registry }}/{{ .Values.docker.image }}:{{ .Values.docker.tag }}'
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: fleet-simulator-config
        env:
        - name: JAVA_OPTS
          value: '{{ .Values.java.options }}'
        ports:
        - name: api
          containerPort: 8080
        resources:
          limits:
            memory: 768Mi
          requests:
            memory: 512Mi
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /actuator/health
            port: api
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /actuator/health
            port: api
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
      priorityClassName: medium-priority
      restartPolicy: Always
      terminationGracePeriodSeconds: 30