apiVersion: v1
kind: Service
metadata:
  name: fleet-simulator
  labels:
    app: fleet-simulator
    version: {{ .Values.docker.tag }}
spec:
  selector:
    app: fleet-simulator
  type: {{ .Values.service.type }}
  ports:
  - name: api
    port: 8080
